### ISSUE TITLE
trace finished from fpga results

### ISSUE THREAD

**Issue by settwi** [umn-impish/umn-detector-code#14]
Looks good overall, i think we should maybe check if the trace is done in fpga_results rather than sleeping. or do both.

_Originally posted by @settwi in https://github.com/umn-impish/umn-detector-code/issues/13#issuecomment-2307057288_

**Comment by WillHonnold** [comment]
$

**Comment by WillHonnold** [comment]
I made it so a trace acquisition will check the results register before saving and log an error otherwise.

**Comment by settwi** [comment]
@WillHonnold please revert your commit and make it on a new branch. i want to review it before you merge it to main
